
name = "s51journal"
main = "src/index.ts"
compatibility_date = "2026-02-25"

type = "javascript"

# KV namespaces
kv_namespaces = [
  { binding = "FEED_STATE", id = "" },
  { binding = "SENT_HASHES", id = "" }
]

# GitHub integration (اختیاری)
[triggers] 
cron = "* * * * *"  # هر 1 دقیقه
