name = 's51journal'
main = "src/index.ts"
compatibility_date = "2026-02-25"

kv_namespaces = [
  { binding = "FEED_STATE", id = "7d83d3259daa4ce0b7e0022732db8ccd" },
  { binding = "SENT_HASHES", id = "5f73aa33e565471cb9c740df4402b144" }
]
